//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PgoWeather
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PgoWeather()
        {
            this.PokemonTypes = new HashSet<PokemonType>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> IsDay { get; set; }
        public Nullable<bool> IsNight { get; set; }
        public string Friendly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PokemonType> PokemonTypes { get; set; }
    }
}
