//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PokeUser
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string TrainerName { get; set; }
        public Nullable<int> TrainerLevel { get; set; }
        public string DiscordName { get; set; }
        public string DiscordTag { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.Guid> ResetToken { get; set; }
        public string PwdHash { get; set; }
    }
}
