//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeatherEntry()
        {
            this.WeatherValues = new HashSet<WeatherValue>();
        }
    
        public long Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Hour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeatherValue> WeatherValues { get; set; }
    }
}
