//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherTranslation
    {
        public int Id { get; set; }
        public string IconText { get; set; }
        public Nullable<bool> CanWindy { get; set; }
        public Nullable<bool> IsDay { get; set; }
        public Nullable<bool> IsNight { get; set; }
        public Nullable<int> PgoIconId { get; set; }
        public Nullable<double> WindOverrideVal { get; set; }
    
        public virtual PgoWeather PgoWeather { get; set; }
    }
}
