//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherValue
    {
        public long Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> WeatherIcon { get; set; }
        public string IconPhrase { get; set; }
        public Nullable<bool> IsDaylight { get; set; }
        public Nullable<double> TempValue { get; set; }
        public string TempUnit { get; set; }
        public Nullable<double> WindSpeed { get; set; }
        public string WindUnit { get; set; }
        public Nullable<double> GustSpeed { get; set; }
        public string GustUnit { get; set; }
        public Nullable<double> PrecipitationProbability { get; set; }
        public Nullable<double> RainProbability { get; set; }
        public Nullable<double> SnowProbability { get; set; }
        public Nullable<double> IceProbability { get; set; }
        public Nullable<double> CloudCover { get; set; }
        public Nullable<double> RainAmt { get; set; }
        public string RainUnit { get; set; }
        public Nullable<double> SnowAmt { get; set; }
        public string SnowUnit { get; set; }
        public Nullable<double> IceAmt { get; set; }
        public string IceUnit { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public Nullable<long> EntryId { get; set; }
        public string ActualIcon { get; set; }
        public string CalculatedIcon { get; set; }
        public Nullable<bool> IsBaseHour { get; set; }
        public Nullable<int> PgoIconId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> ActualIconid { get; set; }
    
        public virtual PgoWeather PgoWeather { get; set; }
    }
}
